export const DEBUG_LEVEL = {
  FORCE: -1,
  SILENT: 0,
  TINY: 1,
  BASIC: 2,
  DETAIL: 3,
};

export const LOG_CONTEXT = {
  INTERNAL_SERVER_ERROR: 'InternalServerError',
  CONFIG: 'Config',
  TOKEN_DECORATOR: 'TokenDataDecorator',
  KAFKA_CONSUMER: 'kafkafConsumer',
  SERVER: 'Server',
  LOGIC: 'Logic',
  UNCATCHED_ERROR: 'UncatchedError',
  REDIS: 'Redis',
  MONGOOSE: 'Mongoose',
  MONGODB: 'MongoDB',
  KAFKA_CLIENT: 'KafkaClient',
  RABBITMQ: 'RabbitMQ',
  HTTP: 'Http',
  CACHE: 'CacheManager',
  TELEGRAM: 'Telegram',
  REQUEST_HTTP: 'RequestHttp',
  REQUEST_GRPC: 'RequestGRPC',
  RESPONSE_HTTP: 'ResponseHttp',
  RESPONSE_GRPC: 'ResponseGRPC',
  JOI_VALIDATION_PIPE: 'JoiValidationPipe',
  MONGO_REPOSITORY: 'MongoRepository',
};
